leftnav:
- identifier: 98a9c792-bda9-4461-bbd0-607b3fcafd02
  name: Marguerite de Roberval Website
  pageRef: /external-resources/marguerite-de-roberval-website_98a9c792-bda9-4461-bbd0-607b3fcafd02
  weight: 10
